version: "3.8"
services:
  devel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: $ROS_DISTRO
    image: oriserobotics/ros-$ROS_DISTRO:devel
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY
      - COLCON_WORKSPACE_FOLDER=$COLCON_WORKSPACE_FOLDER
      - USER=$DOCKER_USER
    network_mode: host
    volumes:
      - ~/.ssh/known_hosts:/home/$DOCKER_USER/.ssh/known_hosts:rw
      - ~/.ssh/id_rsa:/home/$DOCKER_USER/.ssh/id_rsa:ro
      - ~/.ssh/id_rsa.pub:/home/$DOCKER_USER/.ssh/id_rsa.pub:ro
      - ~/.gitconfig:/etc/gitconfig:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $VOLUMES_FOLDER/$CONTAINER_NAME:/home/$DOCKER_USER:rw
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    working_dir: $COLCON_WORKSPACE_FOLDER
    container_name: $CONTAINER_NAME
    stdin_open: true # docker run -i
    tty: true # docker run -t
    env_file: .env
