name: "docker-deploy-dashing"

on: 
  push:
    branches:
      - master
      - main

env:
  PYTHON_VERSION: 3
  ROS_DISTRO: dashing

jobs:
  dockerhub-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: docker/login-action@v1
      name: Login to DockerHub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - run: docker build --build-arg ROS_DISTRO=$ROS_DISTRO --build-arg PYTHON_VERSION=$PYTHON_VERSION -t orise-robotics/ros-$ROS_DISTRO:devel .
    - run: docker push orise-robotics/ros-$ROS_DISTRO:devel
