name: "docker-build"

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  docker-best-practices:
    strategy:
      matrix:
        include:
          - ros-version: 2
            ros-distro: foxy
            ubuntu-distro: focal
          - ros-version: 2
            ros-distro: dashing
            ubuntu-distro: bionic
    env:
      ROS_VERSION: ${{ matrix.ros-version }}
      UBUNTU_DISTRO: ${{ matrix.ubuntu-distro }}
      ROS_DISTRO: ${{ matrix.ros-distro }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: docker build --build-arg ROS_VERSION=$ROS_VERSION --build-arg UBUNTU_DISTRO=$UBUNTU_DISTRO --build-arg ROS_DISTRO=$ROS_DISTRO --target devel-build -t ros$ROS_VERSION-$ROS_DISTRO:devel .
      
    - uses: Azure/container-scan@v0
      with:
        image-name: ros${{ env.ROS_VERSION }}-${{ env.ROS_DISTRO }}:devel
