name: "Check docker image vulnerabilities"

on: 
  pull_request:
  workflow_dispatch:

env:
  ROS_VERSION: 2
  UBUNTU_DISTRO: focal
  ROS_DISTRO: foxy

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: docker build --build-arg ROS_VERSION=$ROS_VERSION --build-arg UBUNTU_DISTRO=$UBUNTU_DISTRO --build-arg ROS_DISTRO=$ROS_DISTRO --target devel-build -t ros2-foxy:devel .
      
    - uses: Azure/container-scan@v0
      with:
        image-name: ros2-foxy:devel
