name: "Check docker image vulnerabilities"

on: 
  pull_request:
  workflow_dispatch:

env:
  ROS_VERSION: 2
  UBUNTU_DISTRO: bionic
  ROS_DISTRO: dashing

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: docker build --build-arg ROS_VERSION=$ROS_VERSION --build-arg UBUNTU_DISTRO=$UBUNTU_DISTRO --build-arg ROS_DISTRO=$ROS_DISTRO --target devel-build -t ros$ROS_VERSION-$ROS_DISTRO:devel .
      
    - uses: Azure/container-scan@v0
      with:
        image-name: ros${{ env.ROS_VERSION }}-${{ env.ROS_DISTRO }}:devel
