name: "docker-build"

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  docker-best-practices:
    strategy:
      matrix:
        include:
          - python-version: 3
            ros-distro: foxy
          - python-version: 3
            ros-distro: dashing
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      ROS_DISTRO: ${{ matrix.ros-distro }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: docker build --build-arg ROS_DISTRO=$ROS_DISTRO --build-arg PYTHON_VERSION=$PYTHON_VERSION -t orise-robotics/ros-$ROS_DISTRO:devel .
      
    - uses: Azure/container-scan@v0
      with:
        image-name: orise-robotics/ros-${{ env.ROS_DISTRO }}:devel
