on: 
  push:
    branches:
      - master
      - main

env:
  ROS_VERSION: 2
  UBUNTU_DISTRO: bionic
  ROS_DISTRO: foxy

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build --build-arg ROS_VERSION=$ROS_VERSION --build-arg UBUNTU_DISTRO=$UBUNTU_DISTRO --build-arg ROS_DISTRO=$ROS_DISTRO --target devel-build -t ros$ROS_VERSION-$ROS_DISTRO:devel .
      
    - uses: Azure/container-scan@v0
      with:
        image-name: ros${{ env.ROS_VERSION }}-${{ env.ROS_DISTRO }}:devel
    
    - uses: docker/login-action@v1
      name: Login to DockerHub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - run: docker tag ros$ROS_VERSION-$ROS_DISTRO:devel openbr/ros$ROS_VERSION-$ROS_DISTRO:devel
    - run: docker push openbr/ros$ROS_VERSION-$ROS_DISTRO:devel
