name: "docker-deploy-dashing"

on: 
  push:
    branches:
      - master
      - main

env:
  ROS_VERSION: 2
  UBUNTU_DISTRO: bionic
  ROS_DISTRO: dashing

jobs:
  dockerhub-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: docker/login-action@v1
      name: Login to DockerHub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - run: docker tag ros-$ROS_DISTRO:devel openbr/ros-$ROS_DISTRO:devel
    - run: docker push openbr/ros-$ROS_DISTRO:devel
